Frequency:
  type: entity
  table: frequencies
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    tripId:
      type: string
    startTime:
      type: time
    endTime:
      type: time
    headwaySecs:
      type: integer
    exactTimes:
      type: integer
      nullable: TRUE